#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export OPSCODE_USER=rocklin
export EDITOR=vim
export VISUAL=gvim

alias qd='TZ=UTC date +"%Y-%m-%d-%T%:::z"'

autoload -Uz promptinit
promptinit
prompt giddie

