#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export OPSCODE_USER=rocklin
export EDITOR=vim
export VISUAL=gvim

RUBIES+=(
  /opt/chefdk/embedded
)

function chefdk() {
  chruby embedded
  eval "$(chef shell-init zsh 2&> /dev/null)"
  extra_paths=(
    /opt/chefdk/bin
  )

  for i in $extra_paths; do
    path=($i ${(@)path:#$i})
  done 
}

function unchefdk() {
  unset GEM_PATH
  unset GEM_HOME
  unset GEM_ROOT
  chef_ruby_version=`ruby -v | cut -f2 -d ' ' | cut -f1 -d'p'`
  chruby system
  
  extra_paths=(
    /opt/chefdk/bin
    $HOME/.gem/ruby/$chef_ruby_version/bin
    $HOME/.chefdk/gem/ruby/2.1.0/bin
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/bin
  )

  for i in $extra_paths; do
    path=(${(@)path:#$i})
  done 
}

autoload -Uz promptinit
promptinit
prompt giddie

